title: Bruno Franca  
email: Brunofrancasecdev@gmail.com 

description: >-
  Blogging about software project and how I realize than

#URL settings
domain: ""
permalink: pretty
url: "" # the base hostname & protocol for your site, e.g. http://example.com


source: _src

extlinks:
  attributes:
    class: external

relative_links:
  enabled: true
  collections: true

sass:
  style: compact

kramdown:
  syntx_highlighter: coderay


include: [".well-known"]

collections:
  posts:
    output: true
    permalink: /blog/:path/index:output_ext
    name: Posts

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post.html"
      nav_current: "/blog/"
  -
    scope:
      path: ""
    values:
      layout: "default.html"
      language: "en"
      author: "Maíra Canal"
